### PR TITLE
add mount

### LINKED ISSUE #42: koa-mount + koa2 + koa-convert + koa-router
I know you got a lot of issue on koa2. I went over them. There are 2 concrete suggestions:

1 - use koa-convert - does not work when the mounted app use koa-router@next.
2 - use https://github.com/coderhaoxin/mount/tree/next-by-promise - works but not published to npm which is bad for forward compatibility.

would you consider reviewing the workflow with koa-convert or re-introducing the 'next-by-promise' branch as a published npm lib/tag?

### PR DESCRIPTION
**Pull request by haoxins**
resolve https://github.com/koajs/mount/issues/42

### CODE REVIEW

**Comment by gyson** [comment]
What `koa-convert` is doing: convert koa 1 middleware to koa 2 middleware

What `koa-mount` is doing: convert koa 1 app to koa 1 middleware

What this pull request is doing: convert koa 2 app to koa 2 middleware

Would it make more sense to add this functionality to `koa-mount@next` ?

**Comment by tejasmanohar** [comment]
I don't think this belongs in koa-convert @coderhaoxin.

**Comment by haoxins** [comment]
Yes, it doesn't belong to `koa-convert` normally. It should be `koa-mount@next`.
Just think the `Promise` changes are noisy (in `koa-mount`'s tests, examples :cry:).
And just as `koa-convert` converts koa 1 middleware to koa 2 middleware,
I treat `mount` as a `atypic` middleware here, alias the converted `mount` IMO.

**Comment by tejasmanohar** [comment]
I'd rather koa-convert not know anything about mount. Totally cool with a separate module that extends koa-convert though or koa-mount@next.

**Pull request closed without merging**
